{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.\n"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 121\u001b[0m, in \u001b[0;36mNewsViewer.show_news\u001b[1;34m(self, item)\u001b[0m\n\u001b[0;32m    119\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"📜 선택한 뉴스 본문 표시\"\"\"\u001b[39;00m\n\u001b[0;32m    120\u001b[0m index \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnews_list\u001b[38;5;241m.\u001b[39mrow(item)\n\u001b[1;32m--> 121\u001b[0m title, link, content \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnews_data\u001b[49m\u001b[43m[\u001b[49m\u001b[43mindex\u001b[49m\u001b[43m]\u001b[49m\n\u001b[0;32m    123\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtitle_label\u001b[38;5;241m.\u001b[39msetText(title)\n\u001b[0;32m    124\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mnews_content\u001b[38;5;241m.\u001b[39msetText(content)\n",
      "\u001b[1;31mIndexError\u001b[0m: list index out of range"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "0",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\82106\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\IPython\\core\\interactiveshell.py:3587: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import csv\n",
    "import os\n",
    "import webbrowser\n",
    "from transformers import BartForConditionalGeneration, PreTrainedTokenizerFast\n",
    "from PyQt5.QtWidgets import QApplication, QMainWindow, QListWidget, QLabel, QTextEdit, QPushButton, QVBoxLayout, QHBoxLayout, QWidget, QLineEdit\n",
    "from PyQt5.QtGui import QFont\n",
    "\n",
    "# ✅ CSV 파일 경로\n",
    "CSV_FILE_PATH = r\"C:\\pthon_basic\\webcrolingProject\\news_crawler_project\\data\\naver_news.csv\"\n",
    "\n",
    "# KoBART 모델 경로\n",
    "MODEL_PATH = \"digit82/kobart-summarization\"\n",
    "tokenizer = PreTrainedTokenizerFast.from_pretrained(MODEL_PATH)\n",
    "model = BartForConditionalGeneration.from_pretrained(MODEL_PATH)\n",
    "\n",
    "class NewsViewer(QMainWindow):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "\n",
    "        # 윈도우 설정\n",
    "        self.setWindowTitle(\"네이버 경제 뉴스 뷰어\")\n",
    "        self.setGeometry(100, 100, 900, 650)  # 창 크기 조정\n",
    "\n",
    "        # 메인 레이아웃\n",
    "        layout = QHBoxLayout()\n",
    "\n",
    "        # 🔍 왼쪽 검색창 및 뉴스 리스트\n",
    "        left_layout = QVBoxLayout()\n",
    "\n",
    "        self.search_input = QLineEdit(self)\n",
    "        self.search_input.setPlaceholderText(\"🔍 검색어 입력 후 Enter\")\n",
    "        self.search_input.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.search_input.returnPressed.connect(self.update_news_list)\n",
    "        left_layout.addWidget(self.search_input)\n",
    "\n",
    "        # 📌 뉴스 리스트\n",
    "        self.news_list = QListWidget(self)\n",
    "        self.news_list.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.news_list.itemClicked.connect(self.show_news)\n",
    "        left_layout.addWidget(self.news_list)\n",
    "\n",
    "        # 뉴스 불러오기 버튼\n",
    "        self.load_button = QPushButton(\"🔄 뉴스 불러오기\", self)\n",
    "        self.load_button.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.load_button.clicked.connect(self.load_news)\n",
    "        left_layout.addWidget(self.load_button)\n",
    "\n",
    "        # 오른쪽 뉴스 제목과 본문 표시 레이아웃\n",
    "        right_layout = QVBoxLayout()\n",
    "\n",
    "        # 📰 뉴스 제목\n",
    "        self.title_label = QLabel(\"뉴스 제목\", self)\n",
    "        self.title_label.setFont(QFont(\"맑은 고딕\", 16, QFont.Weight.Bold))\n",
    "        right_layout.addWidget(self.title_label)\n",
    "\n",
    "        # 📜 뉴스 본문\n",
    "        self.news_content = QTextEdit(self)\n",
    "        self.news_content.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.news_content.setReadOnly(True)\n",
    "        right_layout.addWidget(self.news_content)\n",
    "\n",
    "        # 요약 버튼 추가\n",
    "        self.summarize_button = QPushButton(\"📑 요약하기\", self)\n",
    "        self.summarize_button.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.summarize_button.clicked.connect(self.summarize_news)\n",
    "        right_layout.addWidget(self.summarize_button)\n",
    "\n",
    "        # 뉴스 링크 (클릭하면 웹에서 열림)\n",
    "        self.link_label = QLabel(\"\", self)\n",
    "        self.link_label.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.link_label.setStyleSheet(\"color: blue; text-decoration: underline; cursor: pointer;\")\n",
    "        self.link_label.mousePressEvent = self.open_link\n",
    "        right_layout.addWidget(self.link_label)\n",
    "\n",
    "        layout.addLayout(left_layout)\n",
    "        layout.addLayout(right_layout)\n",
    "\n",
    "        # 중앙 위젯 설정\n",
    "        central_widget = QWidget()\n",
    "        central_widget.setLayout(layout)\n",
    "        self.setCentralWidget(central_widget)\n",
    "\n",
    "        # 뉴스 데이터 저장할 리스트\n",
    "        self.news_data = []\n",
    "        self.load_news()\n",
    "\n",
    "    def load_news(self):\n",
    "        \"\"\"📌 CSV 파일에서 뉴스 데이터 불러오기\"\"\"\n",
    "        self.news_list.clear()\n",
    "        self.news_data.clear()\n",
    "\n",
    "        if not os.path.exists(CSV_FILE_PATH):\n",
    "            self.news_list.addItem(\"⚠️ 뉴스 파일을 찾을 수 없습니다!\")\n",
    "            return\n",
    "\n",
    "        try:\n",
    "            with open(CSV_FILE_PATH, \"r\", encoding=\"utf-8\") as file:\n",
    "                reader = csv.reader(file)\n",
    "                next(reader)  # 첫 번째 줄(헤더) 건너뛰기\n",
    "                for row in reader:\n",
    "                    if len(row) < 3:\n",
    "                        continue\n",
    "                    title, link, content = row\n",
    "                    self.news_data.append((title, link, content))\n",
    "                    self.news_list.addItem(title)  # 뉴스 제목 리스트에 추가\n",
    "        except Exception as e:\n",
    "            self.news_list.addItem(f\"❌ 파일 읽기 오류: {e}\")\n",
    "\n",
    "    def update_news_list(self):\n",
    "        \"\"\"🔍 검색 기능 - 키워드가 포함된 뉴스만 표시\"\"\"\n",
    "        keyword = self.search_input.text().strip().lower()\n",
    "        self.news_list.clear()\n",
    "        for title, link, content in self.news_data:\n",
    "            if keyword in title.lower() or keyword in content.lower():\n",
    "                self.news_list.addItem(title)\n",
    "\n",
    "    def show_news(self, item):\n",
    "        \"\"\"📜 선택한 뉴스 본문 표시\"\"\"\n",
    "        index = self.news_list.row(item)\n",
    "        title, link, content = self.news_data[index]\n",
    "\n",
    "        self.title_label.setText(title)\n",
    "        self.news_content.setText(content)\n",
    "        self.link_label.setText(link)\n",
    "\n",
    "        self.link_label.setStyleSheet(\"color: blue; text-decoration: underline; cursor: pointer;\")\n",
    "        self.current_link = link\n",
    "\n",
    "    def open_link(self, event):\n",
    "        \"\"\"🌐 웹 브라우저에서 뉴스 링크 열기\"\"\"\n",
    "        if hasattr(self, \"current_link\"):\n",
    "            webbrowser.open(self.current_link)\n",
    "\n",
    "    def summarize_news(self):\n",
    "        \"\"\"📑 KoBART 모델을 이용해 뉴스 본문 요약\"\"\"\n",
    "        content = self.news_content.toPlainText()\n",
    "        inputs = tokenizer.encode(\"summarize: \" + content, return_tensors=\"pt\")\n",
    "\n",
    "        summary_ids = model.generate(\n",
    "            inputs,\n",
    "            max_length=150,\n",
    "            num_beams=4,\n",
    "            no_repeat_ngram_size=2,\n",
    "            early_stopping=True\n",
    "        )\n",
    "\n",
    "        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)\n",
    "        self.news_content.setText(summary)\n",
    "\n",
    "# 실행 코드\n",
    "if __name__ == \"__main__\":\n",
    "    app = QApplication(sys.argv)\n",
    "    viewer = NewsViewer()\n",
    "    viewer.show()\n",
    "    sys.exit(app.exec_())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "You passed along `num_labels=3` with an incompatible id to label map: {'0': 'NEGATIVE', '1': 'POSITIVE'}. The number of labels wil be overwritten to 2.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "0"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import sys\n",
    "import csv\n",
    "import os\n",
    "import webbrowser\n",
    "from transformers import BartForConditionalGeneration, PreTrainedTokenizerFast\n",
    "from PyQt5.QtWidgets import QApplication, QMainWindow, QListWidget, QLabel, QTextEdit, QPushButton, QVBoxLayout, QHBoxLayout, QWidget, QLineEdit\n",
    "from PyQt5.QtGui import QFont\n",
    "\n",
    "# ✅ CSV 파일 경로\n",
    "CSV_FILE_PATH = r\"C:\\pthon_basic\\webcrolingProject\\news_crawler_project\\data\\naver_news.csv\"\n",
    "\n",
    "# ✅ KoBART 모델 로드\n",
    "MODEL_PATH = \"digit82/kobart-summarization\"\n",
    "tokenizer = PreTrainedTokenizerFast.from_pretrained(MODEL_PATH)\n",
    "model = BartForConditionalGeneration.from_pretrained(MODEL_PATH)\n",
    "\n",
    "class NewsViewer(QMainWindow):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "\n",
    "        self.setWindowTitle(\"네이버 경제 뉴스 뷰어\")\n",
    "        self.setGeometry(100, 100, 900, 650)\n",
    "\n",
    "        layout = QHBoxLayout()\n",
    "        left_layout = QVBoxLayout()\n",
    "\n",
    "        self.search_input = QLineEdit(self)\n",
    "        self.search_input.setPlaceholderText(\"🔍 검색어 입력 후 Enter\")\n",
    "        self.search_input.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.search_input.returnPressed.connect(self.update_news_list)\n",
    "        left_layout.addWidget(self.search_input)\n",
    "\n",
    "        self.news_list = QListWidget(self)\n",
    "        self.news_list.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.news_list.itemClicked.connect(self.show_news)\n",
    "        left_layout.addWidget(self.news_list)\n",
    "\n",
    "        self.load_button = QPushButton(\"🔄 뉴스 불러오기\", self)\n",
    "        self.load_button.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.load_button.clicked.connect(self.load_news)\n",
    "        left_layout.addWidget(self.load_button)\n",
    "\n",
    "        right_layout = QVBoxLayout()\n",
    "\n",
    "        self.title_label = QLabel(\"뉴스 제목\", self)\n",
    "        self.title_label.setFont(QFont(\"맑은 고딕\", 16, QFont.Weight.Bold))\n",
    "        right_layout.addWidget(self.title_label)\n",
    "\n",
    "        self.news_content = QTextEdit(self)\n",
    "        self.news_content.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.news_content.setReadOnly(True)\n",
    "        right_layout.addWidget(self.news_content)\n",
    "\n",
    "        self.summarize_button = QPushButton(\"📑 요약하기\", self)\n",
    "        self.summarize_button.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.summarize_button.clicked.connect(self.summarize_news)\n",
    "        right_layout.addWidget(self.summarize_button)\n",
    "\n",
    "        self.link_label = QLabel(\"\", self)\n",
    "        self.link_label.setFont(QFont(\"맑은 고딕\", 14))\n",
    "        self.link_label.setStyleSheet(\"color: blue; text-decoration: underline; cursor: pointer;\")\n",
    "        self.link_label.mousePressEvent = self.open_link\n",
    "        right_layout.addWidget(self.link_label)\n",
    "\n",
    "        layout.addLayout(left_layout)\n",
    "        layout.addLayout(right_layout)\n",
    "\n",
    "        central_widget = QWidget()\n",
    "        central_widget.setLayout(layout)\n",
    "        self.setCentralWidget(central_widget)\n",
    "\n",
    "        self.news_data = []\n",
    "        self.filtered_news_data = []\n",
    "\n",
    "        self.load_news()\n",
    "\n",
    "    def load_news(self):\n",
    "        self.news_list.clear()\n",
    "        self.news_data.clear()\n",
    "        self.filtered_news_data.clear()\n",
    "\n",
    "        if not os.path.exists(CSV_FILE_PATH):\n",
    "            self.news_list.addItem(\"⚠️ 뉴스 파일을 찾을 수 없습니다!\")\n",
    "            return\n",
    "\n",
    "        try:\n",
    "            with open(CSV_FILE_PATH, \"r\", encoding=\"utf-8\") as file:\n",
    "                reader = csv.reader(file)\n",
    "                next(reader)  # 헤더 건너뛰기\n",
    "                for row in reader:\n",
    "                    if len(row) < 3:\n",
    "                        continue\n",
    "                    title, link, content = row[:3]  # 앞의 3개만 가져옴\n",
    "                    self.news_data.append((title, link, content))\n",
    "\n",
    "            self.filtered_news_data = self.news_data.copy()\n",
    "            for title, _, _ in self.filtered_news_data:\n",
    "                self.news_list.addItem(title)\n",
    "\n",
    "        except Exception as e:\n",
    "            self.news_list.addItem(f\"❌ 파일 읽기 오류: {e}\")\n",
    "\n",
    "    def update_news_list(self):\n",
    "        keyword = self.search_input.text().strip().lower()\n",
    "        self.news_list.clear()\n",
    "\n",
    "        self.filtered_news_data = [\n",
    "            (title, link, content)\n",
    "            for title, link, content in self.news_data\n",
    "            if keyword in title.lower() or keyword in content.lower()\n",
    "        ]\n",
    "\n",
    "        for title, _, _ in self.filtered_news_data:\n",
    "            self.news_list.addItem(title)\n",
    "\n",
    "    def show_news(self, item):\n",
    "        index = self.news_list.row(item)\n",
    "        if 0 <= index < len(self.filtered_news_data):\n",
    "            title, link, content = self.filtered_news_data[index]\n",
    "            self.title_label.setText(title)\n",
    "            self.news_content.setText(content)\n",
    "            self.link_label.setText(link)\n",
    "            self.current_link = link\n",
    "\n",
    "    def open_link(self, event):\n",
    "        if hasattr(self, \"current_link\"):\n",
    "            webbrowser.open(self.current_link)\n",
    "\n",
    "    def summarize_news(self):\n",
    "        content = self.news_content.toPlainText().strip()\n",
    "        if not content:\n",
    "            return\n",
    "\n",
    "        inputs = tokenizer.encode(\"summarize: \" + content, return_tensors=\"pt\")\n",
    "        summary_ids = model.generate(\n",
    "            inputs,\n",
    "            max_length=150,\n",
    "            num_beams=4,\n",
    "            no_repeat_ngram_size=2,\n",
    "            early_stopping=True\n",
    "        )\n",
    "        summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)\n",
    "        self.news_content.setText(summary)\n",
    "\n",
    "# ✅ Jupyter에서 실행\n",
    "app = QApplication.instance() or QApplication(sys.argv)\n",
    "viewer = NewsViewer()\n",
    "viewer.show()\n",
    "app.exec_()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
